spring.application.name=Project_Java_WebService_quanlykhoahocvachamdiem
spring.datasource.url=jdbc:mysql://localhost:3306/course_management
spring.datasource.username=root
spring.datasource.password=1234567890

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6375